apiVersion: v1
kind: Service
metadata:
  annotations:
    NAME: rabbitmq
    kompose.cmd: C:\Program Files\kompose\kompose.exe convert -f docker-compose-prod.yml
      -o deploy
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: rabbit
  name: rabbit
spec:
  ports:
  - name: "5672"
    port: 5672
    targetPort: 5672
  - name: "15672"
    port: 15672
    targetPort: 15672
  selector:
    io.kompose.service: rabbit
status:
  loadBalancer: {}
