// Copyright 2020 Paingha Joe Alagoa. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package main

import (
	"context"

	"bitbucket.com/irb/api/config"
	"bitbucket.com/irb/api/models"
	"bitbucket.com/irb/api/plugins"
	"bitbucket.com/irb/api/routes"
	"bitbucket.com/irb/api/service"
	"bitbucket.com/irb/api/stuff"
	"github.com/jinzhu/gorm"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	_ "bitbucket.com/irb/api/docs" // docs is generated by Swag CLI, you have to import it.
)

// @title NSU IRB API
// @version 1.0
// @description This is an api server for NSU IRB.
// @termsOfService http://swagger.io/terms/

// @contact.name Paingha Joe Alagoa
// @contact.url https://github.com/paingha
// @contact.email apaingha@gmail.com
// @schemes http https ws
// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8080
// @BasePath /v1
var err error

func main() {
	//system config
	systemCfg := &config.SystemConfig{}
	if err := config.InitConfig(systemCfg); err != nil {
		plugins.LogFatal("API", "Wrong rabbitMQ config", err)
	}
	// Connect to Database
	config.DB, err = gorm.Open("postgres", config.GetConnectionContext())
	if err != nil {
		plugins.LogFatal("API", "Database connection error", err)
	}
	defer config.DB.Close()
	config.DB.LogMode(true)
	config.DB.AutoMigrate(&models.User{})
	config.DB.AutoMigrate(&models.Conversation{})
	config.DB.AutoMigrate(&models.Message{})
	config.DB.AutoMigrate(&models.Application{})
	localServer := ":8089"
	mailService, err := service.NewQueueService(context.Background(), systemCfg)
	if err != nil {
		plugins.LogError("API", "error initializing mail service", err)
	}
	stuff.MailService = mailService
	smsService, err := service.NewQueueService(context.Background(), systemCfg)
	if err != nil {
		plugins.LogError("API", "error initializing sms service", err)
	}
	stuff.SmsService = smsService
	pushService, err := service.NewQueueService(context.Background(), systemCfg)
	if err != nil {
		plugins.LogError("API", "error initializing push service", err)
	}
	stuff.PushService = pushService
	uploadService, err := service.NewQueueService(context.Background(), systemCfg)
	if err != nil {
		plugins.LogError("API", "error initializing upload service", err)
	}
	stuff.UploadService = uploadService
	inboxHub := plugins.NewHub()
	go inboxHub.Run()
	//setup routes
	r := routes.SetupRouter(inboxHub)
	url := ginSwagger.URL("http://localhost:8080/swagger/doc.json") // The url pointing to API definition
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, url))
	// running
	if err := r.Run(localServer); err != nil {
		plugins.LogFatal("API", "An Error occured while starting the server", err)
	}
}
